### ISSUE TITLE
force closes 

### ISSUE THREAD

**Issue by Dirkstaal** [harjot-oberai/MusicStreamer#8]
hi every time i try to run the apk it closes before the apk is started i can send logs if it will help

**Comment by Dirkstaal** [comment]
i really like the looks its s pity it force closes when i try to open i have an Api 20 device 
here's the error i get after the apk force closes

06-21 07:49:18.580 13594-13594/com.sdsmdg.harjot.MusicDNA E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.sdsmdg.harjot.MusicDNA, PID: 13594
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sdsmdg.harjot.MusicDNA/com.sdsmdg.harjot.MusicDNA.SplashActivity}: java.lang.RuntimeException: native typeface cannot be made
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:166)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5590)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
                                                                                at dalvik.system.NativeStart.main(Native Method)
                                                                             Caused by: java.lang.RuntimeException: native typeface cannot be made
                                                                                at android.graphics.Typeface.<init>(Typeface.java:334)
                                                                                at android.graphics.Typeface.createFromAsset(Typeface.java:308)
                                                                                at com.sdsmdg.harjot.MusicDNA.SplashActivity.onCreate(SplashActivity.java:44)
                                                                                at android.app.Activity.performCreate(Activity.java:5447)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:166) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5590) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096) 
                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by harjot-oberai** [comment]
This is a minor issue related to Typeface initialization.
Can you tell me which apk you used, and where did you get it ?

**Comment by harjot-oberai** [comment]
If you build the project from source code, then you have to add the required typefaces to "build/assets/fonts" folder.
the "build" folder is not pushed to github, that is why app crashes, I've fixed the issue, now you should be able to run the app with default typefaces.

**Comment by Dirkstaal** [comment]
ive imported it with android studio and then runned it on my android i
would really like it to work because i have a lot of visualizations that i
can impliment if it works
